#!/bin/bash

#  Copyright DataStax, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


export JAVA_OPTS="--add-modules jdk.incubator.vector"
if [ ! -d "jvector-examples/target/classes" -o "$1" = "-r" ]
then
 shift
 printf "building project before invoking testrig...\n" 1>&2
 mvn -Pjdk22 compile package -pl :jvector-examples -am -DskipTests
 status=$?
 if (( status != 0 ))
 then
  printf "failed build, resolve issues before trying to run testrig\n"
  exit $status
 else
  printf "built project successfully, continuing...\n" 1>&2
  echo -e "\a"
  sleep 1
  echo -e "\a"
  sleep 1
 fi
fi

java $JAVA_OPTS -Xmx32g -jar ./jvector-examples/target/jvector-examples-*-SNAPSHOT-jar-with-dependencies.jar $*
