yamlSchemaVersion: 1
onDiskIndexVersion: 7
benchmarks:
  throughput: [AVG]
  latency: [AVG, P999]
  count: [visited, expanded, expanded base layer]
  accuracy: [recall]
console:
  benchmarks:
    throughput: [AVG]
    latency: [AVG, P999]
    count: [visited, expanded, expanded base layer]
    accuracy: [recall]
  metrics:
    construction: [index_build_time_s, index_quant_time_s, search_quant_time_s]
logging:
  dir: logging
  jvectorRef: "ash-dev"
  runId: "ash-64x-integrated-{ts}"
  type: csv
  benchmarks:
    throughput: [AVG]
    latency: [AVG, P999]
    count: [visited, expanded, expanded base layer]
    accuracy: [recall]
  metrics:
    construction: [index_build_time_s, index_quant_time_s, search_quant_time_s]
