name: Comment on new Pull Request with checklist
on:
  pull_request:
    types: opened

jobs:
  checklist-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Add comment
        run:
          gh pr comment $PRNUM --body-file .github/workflows/pr_checklist.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PRNUM: ${{ github.event.pull_request.number }}
