name: Run Bench Main

on:
  workflow_dispatch:
  push:
    branches: [ main,github_actions ]
    tags: [ '*' ]
  pull_request:

jobs:
  run-bench:
    strategy:
      matrix:
        jdk: [11, 20, 22, 24]
        os: [ubuntu-latest, windows-latest]
        isa: [isa-avx512f]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}

      - name: Set up GCC
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y gcc

      - name: Print ISA info
        if: matrix.os == 'ubuntu-latest'
        run: |
          required="avx2 avx512f avx512cd avx512bw avx512dq avx512v"
          printf "required ISA feature flags: %s\n" "${required}"
          flags="$(lscpu|grep '^Flags'|cut -d: -f2)"
          output=""
          for flag in ${required} ; do
           if [[ " $flags " == *"${flag}"* ]]
           then output="${output} $flag(OK)"
           else output="${output} $flag(FAIL)"
          fi ; done
          printf "%s\n" ${output}
          if [[ " $output " == *"FAIL"* ]]; then
            echo "Warning: Missing required AVX-512 flags. Skipping AVX-512 benchmarks."
            exit 0
          fi

      - name: Build with Maven (JDK 11)
        if: matrix.jdk == '11'
        run: mvn -B -Pjdk11 package --file pom.xml

      - name: Build with Maven (JDK 20)
        if: matrix.jdk == '20'
        run: mvn -B -Pjdk20 package --file pom.xml

      - name: Build with Maven (JDK 22)
        if: matrix.jdk == '22'
        run: mvn -B package --file pom.xml

      - name: Build with Maven (JDK 24)
        if: matrix.jdk == '24'
        run: mvn -B -Punix-amd64-profile package --file pom.xml

      - name: Run Bench main
        run: |
          # Use the jar-with-dependencies which includes all required dependencies
          java ${{ matrix.jdk >= 20 && '--enable-native-access=ALL-UNNAMED --add-modules=jdk.incubator.vector' || '' }} \
            ${{ matrix.jdk >= 22 && '-Djvector.experimental.enable_native_vectorization=true' || '' }} \
            -Xmx4G -jar jvector-examples/target/jvector-examples-*-jar-with-dependencies.jar \
            io.github.jbellis.jvector.example.Bench --output bench-results.json

      - name: Upload Bench Results
        uses: actions/upload-artifact@v4
        with:
          name: bench-results-${{ matrix.os }}-jdk${{ matrix.jdk }}
          path: bench-results.json
