name: Unit Test CI

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/unit-tests.yaml
      - '**.java'
      - '**/pom.xml'

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 11, 20 ]
        os: [ ubuntu-latest, windows-latest, mac-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: temurin
          cache: maven
      - name: Compile and run tests
        run: mvn -B -Pjdk${{ matrix.jdk }} package --file pom.xml
